### PR TITLE
Mongoid 5 compat

### PR DESCRIPTION
**Pull request by spk**
Fellow up PR https://github.com/td-berlin/mongoid_cleaner/pull/4
Thanks to @mkempe
Second try

### CODE REVIEW

**Comment by saschaknobloch** [comment]
@mkempe fyi: we've released `1.1.0` to rubygems.org

**Comment by mentero** [comment]
@saschaknobloch :tada

**Comment by mkempe** [comment]
Nice, many thanks!

**Comment by saschaknobloch** [comment]
Hello @mentero!!1 :D

**Pull request merged**
