### PR TITLE
Mongoid 5 compatibility

### PR DESCRIPTION
**Pull request by mkempe**
Hey there,

first of all, thanks for the Gem!

This Berlin pull request is for Mongoid 5. Can you please look over it again, especially the line `collections_with_options.each { |c| session[c].find.delete_many }`, don't now if `delete_many` is the best method.

Additional i clean up the Gemspec and Rakefile.

Thanks again.

Maik

### CODE REVIEW

**Comment by saschaknobloch** [comment]
Hey Maik,

thanks for collaborating. :-) The problem I initially see, is that we loose support for `mongoid` versions < `5`.
Are you planning to make this PR backwards compatible to version `4`?

**Comment by mkempe** [comment]
Hey Sascha,

thanks for your feedback. A backwards compatible version is difficult, because several methods changed. Have you an idea to keep the backwards compatible? Maybe the way `database_cleaner` handles it? What's your opinion to bump the version to `2.0.0` with support only for Mongoid 5.x?

**Comment by saschaknobloch** [comment]
Hey Maik,

first of all: sorry for the late response.
Regarding compatibility: This Gem should support Mongoid 4 + 5. We don't like to maintain different branches / versions in order to achieve that. So yes, the way `database_cleaner` handles it, could be the way to go. You could inspect 
```ruby
Mongoid::VERSION
```
in order to choose correct methods.

Sascha

**Comment by mkempe** [comment]
Hey Sascha and Laurent,

thanks for your input and special thanks to Laurent for taking over.

I am closing this PR in favour of https://github.com/td-berlin/mongoid_cleaner/issues/6.

**Pull request closed without merging**
